export const feeds = [
     {
    id: 1069417,
    title: 'Backchat',
    url: 'https://podcast.rthk.hk//podcast/backchat.xml',
    originalUrl: 'http://podcast.rthk.org.hk/podcast/backchat.xml',
    link: 'https://podcast.rthk.hk/podcast/item.php?pid=177',
    description: "Backchat is RTHK Radio 3's week-daily current affairs discussion programme, with expert panels and listener participation. It airs every Monday to Friday from 9.05am - 10am (HKT).\n" +
      'Have your say by calling us on 233 88 266, find us on Facebook - Backchat on RTHK Radio 3, or email backchat@rthk.hk  \n' +
      "Listen live on Radio 3's homepage - www.rthk.hk/radio/radio3\n" +
      'The Backchat podcast is available after each live broadcast ',
    author: 'RTHK.HK',
    ownerName: 'RTHK.HK',
    image: 'https://podcast.rthk.hk/podcast/upload_photo/item_photo/1400x1400_177.jpg',
    artwork: 'https://podcast.rthk.hk/podcast/upload_photo/item_photo/1400x1400_177.jpg',
    lastUpdateTime: 1756103180,
    lastCrawlTime: 1756103173,
    lastParseTime: 1756103195,
    inPollingQueue: 0,
    priority: 5,
    lastGoodHttpStatusTime: 1756103173,
    lastHttpStatus: 200,
    contentType: 'text/xml',
    itunesId: 297100250,
    generator: '',
    language: 'en-US',
    type: 0,
    dead: 0,
    crawlErrors: 0,
    parseErrors: 0,
    categories: { '55': 'News', '56': 'Daily' },
    locked: 0,
    explicit: false,
    podcastGuid: '74b96bf9-8e85-529e-9a58-60048f64309f',
    medium: 'podcast',
    episodeCount: 1000,
    imageUrlHash: 3493142075,
    newestItemPubdate: 1756081800
  },
  {
    id: 969230,
    title: 'Hong Kong Heritage',
    url: 'https://podcast.rthk.hk//podcast/hkheritage.xml',
    originalUrl: 'http://podcast.rthk.org.hk/podcast/hkheritage.xml',
    link: 'https://podcast.rthk.hk/podcast/item.php?pid=164',
    description: '                                              \n' +
      'Every week, journalist, broadcaster and local historian, Annemarie Evans, explores Hong Kong, digging up many (often forgotten or unknown) aspects of our cultural, architectural, and artistic heritage. \n' +
      "Listen live via Radio 3's homepage https://www.rthk.hk/radio/radio3\n" +
      ' \n' +
      'Saturdays 7.30am - 8.00am (HKT) - first broadcast\n' +
      'Sundays 6.15pm - 6.45pm (HKT) - repeat broadcast\n' +
      'Podcast available weekly after the first broadcast.  \n' +
      '  If you would like to share your story or some Hong Kong cultural history with us, please email hkhradio3@gmail.com',
    author: 'RTHK.HK',
    ownerName: 'RTHK.HK',
    image: 'https://podcast.rthk.hk/podcast/upload_photo/item_photo/1400x1400_164.jpg',
    artwork: 'https://podcast.rthk.hk/podcast/upload_photo/item_photo/1400x1400_164.jpg',
    lastUpdateTime: 1756102625,
    lastCrawlTime: 1756102623,
    lastParseTime: 1756102629,
    inPollingQueue: 0,
    priority: 3,
    lastGoodHttpStatusTime: 1756102623,
    lastHttpStatus: 200,
    contentType: 'text/xml',
    itunesId: 293202327,
    generator: '',
    language: 'en-US',
    type: 0,
    dead: 0,
    crawlErrors: 0,
    parseErrors: 0,
    categories: { '77': 'Society', '78': 'Culture', '79': 'Documentary' },
    locked: 0,
    explicit: false,
    podcastGuid: '9ffea002-94c7-5e6f-a104-6df5dea93d25',
    medium: 'podcast',
    episodeCount: 755,
    imageUrlHash: 1556723534,
    newestItemPubdate: 1755905400
  },
{
    id: 1079312,
    title: '香港電台：中華五千年',
    url: 'https://podcast.rthk.hk//podcast/china5000.xml',
    originalUrl: 'http://podcast.rthk.hk/podcast/china5000.xml',
    link: 'https://podcast.rthk.hk/podcast/item.php?pid=336',
    description: '中華五千年的歷史，多少風流人物，無數繽紛多彩的故事，化成聲音與文字，助你輕鬆了解中國歷史的輪廓。\n' +
      '香港電台最長壽的歷史教育節目－「中華五千年」，全數九百集，讓你認識由軒轅皇帝至中華人民共和國建國，前後長達五千年的歷史。\n' +
      '節目由魏便利、鄭啟明和梁家永主持，並由香港電台的廣播藝員，以廣播劇形式，演繹精彩的歷史故事。',
    author: 'RTHK.HK',
    ownerName: 'RTHK.HK',
    image: 'https://podcast.rthk.hk/podcast/upload_photo/item_photo/1400x1400_336.jpg',
    artwork: 'https://podcast.rthk.hk/podcast/upload_photo/item_photo/1400x1400_336.jpg',
    lastUpdateTime: 1755357890,
    lastCrawlTime: 1756100543,
    lastParseTime: 1755448986,
    inPollingQueue: 0,
    priority: 3,
    lastGoodHttpStatusTime: 1755448976,
    lastHttpStatus: 200,
    contentType: 'text/xml',
    itunesId: 501626043,
    generator: '',
    language: 'zh-CN',
    type: 0,
    dead: 0,
    crawlErrors: 0,
    parseErrors: 0,
    categories: { '77': 'Society', '78': 'Culture', '79': 'Documentary' },
    locked: 0,
    explicit: false,
    podcastGuid: 'cfd2f32a-b380-5154-9dff-ddfd4a265f90',
    medium: 'podcast',
    episodeCount: 700,
    imageUrlHash: 3780863156,
    newestItemPubdate: 1755351000
  },
  {
    id: 1169829,
    title: '法醫研究所',
    url: 'https://podcast.rthk.hk//podcast/forensic_institute.xml',
    originalUrl: 'http://podcast.rthk.hk/podcast/forensic_institute.xml',
    link: 'https://podcast.rthk.hk/podcast/item.php?pid=1576',
    description: '法醫的工作究竟是怎樣？是否如電視劇描述般，時常要身陷險境、出生入死去查案？非也，就讓梁榮忠和法醫人類學家李衍蒨告訴你，屍骨如何呈現餘音。 \n' +
      '主持: 梁榮忠、李衍蒨\n' +
      '監製: 羅曼穎',
    author: 'RTHK.HK',
    ownerName: 'RTHK.HK',
    image: 'https://podcast.rthk.hk/podcast/upload_photo/item_photo/1400x1400_1576.jpg',
    artwork: 'https://podcast.rthk.hk/podcast/upload_photo/item_photo/1400x1400_1576.jpg',
    lastUpdateTime: 1741599355,
    lastCrawlTime: 1741599351,
    lastParseTime: 1741599357,
    inPollingQueue: 0,
    priority: -1,
    lastGoodHttpStatusTime: 1741599351,
    lastHttpStatus: 200,
    contentType: 'text/xml',
    itunesId: 1460753754,
    generator: '',
    language: 'zh-CN',
    type: 0,
    dead: 0,
    crawlErrors: 0,
    parseErrors: 0,
    categories: { '77': 'Society', '78': 'Culture' },
    locked: 0,
    explicit: false,
    podcastGuid: '9ad6fae7-44db-5b4e-a7e5-27f39d4c5eaa',
    medium: 'podcast',
    episodeCount: 93,
    imageUrlHash: 2000971644,
    newestItemPubdate: 1616853600
  },
  {
    id: 1088464,
    title: '獅子山下  經典重溫',
    url: 'https://podcast.rthk.hk//podcast/tv_belowthelionrockclassics_i.xml',
    originalUrl: 'http://podcast.rthk.hk/podcast/tv_belowthelionrockclassics_i.xml',
    link: 'https://podcast.rthk.hk/podcast/item.php?pid=568',
    description: '每一座城市都有一個主題，這個主題往往由一處名勝，一條河流或一個山脈來代表。香港的主題，由開埠至今都是「逆境自存，群策群力」，這個主題的代表就是獅子山。\n' +
      ' \n' +
      '六、七十年代的香港是一個艱難的年代，但亦是一個充滿活力的時代。當時大部份香港的徙置區、屋邨以及木屋區的居民都居住在獅子山下一帶，他們每天早晨起來，抬頭便看見那座彷似雄獅子般的獅山脈，精神煥發地迎著朝陽，便鼓舞起他們逆境自存，奮鬥不息的精神。《獅子山下》便是那個時代乘勢而出的電視劇集。這個劇集既為小市民訴說心聲，替他們吐苦水；又有為政府闡明政策，增進官民溝通；亦表揚傳統中國人守望相助，同甘共苦的精神。\n' +
      ' \n' +
      '今年正值『港台電視31』啟播， 就讓我們重溫《獅子山下》劇集，去找尋數代香港人熟悉的面孔和風景，還有不同時代的香港人情風貌。全輯共65集一小時，並訪問歴年來參予劇集的幕後工作人員與演員，同時亦加上學者的分析，希望能對大眾有所啟發裨益。\n' +
      '(原播出日期：二零一四年一月十三日起　逢星期一至五晚上九時三十分　港台電視31)',
    author: 'RTHK.HK',
    ownerName: 'RTHK.HK',
    image: 'https://podcast.rthk.hk/podcast/upload_photo/item_photo/1400x1400_568.jpg',
    artwork: 'https://podcast.rthk.hk/podcast/upload_photo/item_photo/1400x1400_568.jpg',
    lastUpdateTime: 1756036464,
    lastCrawlTime: 1756036462,
    lastParseTime: 1756036467,
    inPollingQueue: 0,
    priority: -1,
    lastGoodHttpStatusTime: 1756036462,
    lastHttpStatus: 200,
    contentType: 'text/xml',
    itunesId: 797407388,
    generator: '',
    language: 'zh-CN',
    type: 0,
    dead: 0,
    crawlErrors: 0,
    parseErrors: 0,
    categories: { '104': 'Tv', '105': 'Film' },
    locked: 0,
    explicit: false,
    podcastGuid: 'f1086023-8529-5c64-a18e-b997209576bb',
    medium: 'podcast',
    episodeCount: 65,
    imageUrlHash: 1836482140,
    newestItemPubdate: 1397223000
  }
]